create table person(
                       id int generated by default as identity primary key,
                       full_name varchar (100) not null unique,
                       year_of_birth int not null check ( year_of_birth > 1900 )
);

create table book(
                     id int generated by default as identity primary key,
                     title varchar(100) not null,
                     author varchar(100) not null,
                     year int not null,
                     person_id int references person(id) on delete set null
);

